language: go

go:
  - "1.8"
branches:
  only:
    - hugo 
install:
    - uname -a
    - wget https://github.com/gohugoio/hugo/releases/download/v0.55.4/hugo_0.55.4_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - hugo version
    - ls
    - pwd
script:
  - hugo
deploy:
  local_dir: public
  repo: wotjd/wotjd.github.io
  target_branch: master
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  email: wotjd971102@gmail.com
  name: "wotjd"
  on:
    branch: master