install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - hugo version
script:
  - hugo
deploy:
  local_dir: public
  repo: wotjd/wotjd.github.io
  target_branch: master
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  email: wotjd971102@gmail.com
  name: "wotjd"
  on:
    branch: master