language: go
go:
  - "1.10.1"
install:
  - go get github.com/gohugoio/hugo
script:
  - hugo
deploy:
  local_dir: public
  repo: wotjd/wotjd.github.io
  target_branch: master
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Travis CI 가 깃허브에 직접 업로드 하기위한 토큰
  email: wotjd971102@gmail.com
  name: "wotjd"
  on:
    branch: master